#! /usr/bin/perl -w

use strict;

my $pitem;
my @path;
my @new=();
my %hash=();

@path=($ARGV[0]? (split /:/, $ARGV[0]) : (split /:/, $ENV{PATH}));

foreach $pitem (@path)
    {
    if (!$hash{$pitem}{found})
	{
	$hash{$pitem}{found}=1;
	push @new, $pitem if (-d $pitem);
	}
    else
	{
	print STDERR "Duplicate path entry: \"$pitem\".\n";
	}
    }

print join ":", @new ;
print "\n";
