---
  - name: pb1
    hosts: "{{target}}"
    vars:
      list:
        - apache2
        - apache2-utils
        - nginx
        - openssl
        - ansible
        - ansible-lint
        - rpcbind
        - net-tools
        - procps
        - postfix
        - pylint
        - python3.9
        - python3-pip
        - python3-virtualenv
        - subversion
        - git
        - x11-xserver-utils
        - sshpass
        - xfce4 
        - xfce4-goodies
        - tightvncserver

      piplist:
        - flask
        - urllib3
        - blinkpy
        - pyyaml
        - blinker
        - flasker
        - pytz
        - pathlib
        - tzlocal
        - django
        - ansible
        - ansible-lint

    tasks:
      - name: install stuff
        become: yes
        package: name={{list}} state=latest update_cache=true

      - name: install pip stuff
        become: no
        pip: virtualenv=/home/eolson/venv umask=022 name={{piplist}}

      - name: sysctl stuff keepalive intvl
        become: yes
        ansible.posix.sysctl:
          name: net.ipv4.tcp_keepalive_intvl
          value: '60'

      - name: sysctl stuff keepalive probes
        become: yes
        ansible.posix.sysctl: name=net.ipv4.tcp_keepalive_probes value='5'

      - name: sysctl stuff keepalive time
        become: yes
        ansible.posix.sysctl: name=net.ipv4.tcp_keepalive_time value='300'
